-- Esquema PostgreSQL para Neon.
-- Ejecutar todo este archivo en el SQL Editor de Neon.

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  tipo_documento VARCHAR(10) NOT NULL,
  numero_documento VARCHAR(12) NOT NULL UNIQUE,
  direccion VARCHAR(180) NOT NULL,
  telefono VARCHAR(10) NOT NULL,
  correo VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  estado VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
  rol_id INTEGER NOT NULL REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  reset_token VARCHAR(255),
  reset_token_expira TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS productos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(140) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  detalle TEXT NOT NULL,
  categoria VARCHAR(60) NOT NULL,
  imagen_url VARCHAR(500) NOT NULL,
  precio NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estado VARCHAR(10) NOT NULL DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Agotado', 'Inactivo')),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (nombre) VALUES ('Administrador'), ('Empleado'), ('Cliente')
ON CONFLICT (nombre) DO NOTHING;

CREATE TABLE IF NOT EXISTS pqr (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER NOT NULL REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tipo VARCHAR(8) NOT NULL CHECK (tipo IN ('Peticion', 'Queja', 'Reclamo')),
  asunto VARCHAR(150) NOT NULL,
  mensaje TEXT NOT NULL,
  estado VARCHAR(12) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'En proceso', 'Respondida', 'Cerrada')),
  respuesta TEXT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE SET NULL,
  iniciado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(7) NOT NULL DEFAULT 'Activa' CHECK (estado IN ('Activa', 'Cerrada'))
);

CREATE TABLE IF NOT EXISTS mensajes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id INTEGER NOT NULL REFERENCES conversaciones(id) ON UPDATE CASCADE ON DELETE CASCADE,
  emisor VARCHAR(7) NOT NULL CHECK (emisor IN ('Usuario', 'Bot')),
  contenido TEXT NOT NULL,
  enviado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Imágenes subidas desde el panel de administración. Van en la base porque el
-- disco de una función serverless es de solo lectura y efímero.
CREATE TABLE IF NOT EXISTS imagenes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  tipo_mime VARCHAR(60) NOT NULL,
  contenido BYTEA NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Registro de intentos de acceso para limitar fuerza bruta (login, registro,
-- recuperación). En serverless un contador en memoria no sirve, así que se
-- cuentan filas recientes de esta tabla. Se limpia sola en cada verificación.
CREATE TABLE IF NOT EXISTS intentos_acceso (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(200) NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_intentos_clave_fecha ON intentos_acceso (clave, creado_en);
